# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "25af563cd3ac5927bb0ecd44c47a0ca4"
name = "themeExt"
handle = "themeext-2"
application_url = "https://code-researchers-robust-consolidated.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "fffff12345test.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://code-researchers-robust-consolidated.trycloudflare.com/auth/callback",
  "https://code-researchers-robust-consolidated.trycloudflare.com/auth/shopify/callback",
  "https://code-researchers-robust-consolidated.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
